### PR TITLE
Completed the task !

### PR DESCRIPTION
**Pull request by TheFenrisLycaon**
# Pull Request Template

**file_arranger.py** -

**Finished the script and made an exe as bonus !**

Nothing in the existing codebase was changed.

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by TheFenrisLycaon** [comment]
Now you can merge :3

**Comment by pawangeek** [comment]
That's awesome @TheFenrisLycaon Leave a star ⭐ on repo in self-appreciation of your contribution :)

**Comment by TheFenrisLycaon** [comment]
Aye aye captain !

**Comment by pawangeek** [comment]
@all-contributors add @TheFenrisLycaon for code

**Comment by TheFenrisLycaon** [comment]
Thanks !

**Comment by pawangeek** [comment]
Actually, I add the games section after adding 75 scripts (After the panda stopped playing outdoor games as mentioned in README 😄)  Meanwhile, look at other issues and check if you're able to solve them

**Comment by TheFenrisLycaon** [comment]
I have automated the flappy bird game using neural nets, so I thought it can go here.

**Comment by pawangeek** [comment]
It's more like simulation rather than automation

**Comment by TheFenrisLycaon** [comment]
Hey I put up another comment in the digital clock issue. Can I get that one ?

**Comment by TheFenrisLycaon** [comment]
> It's more like simulation rather than automation

:3 okay.

**Comment by pawangeek** [comment]
> Hey I put up another comment in the digital clock issue. Can I get that one ?

It's already assigned :|

**Comment by TheFenrisLycaon** [comment]
Okay, I'll fish for smt else then.

**Pull request merged**
