### PR TITLE
added script for sms_loc

### PR DESCRIPTION
**Pull request by bunnysworld**
# Pull Request Template

**script name** -sms_loc.py

**Brief about script**
- This script uses Fast2Sms Services to send sms
- Rest information is in README section of this script

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by bunnysworld** [comment]
hey @pawangeek  i dont't know why  i am getting spellcheck error for the changes that i did not make

**Comment by bunnysworld** [comment]
there is some spellcheck error while making PR for the  " zip_password_cracker '' folder and this script does not belongs to me 
what should i do kindly guide @pawangeek

**Comment by pawangeek** [comment]
Seems to be perfect @bunnysworld

**Comment by pawangeek** [comment]
@all-contrubutors add @bunnysworld for code

**Comment by pawangeek** [comment]
@all-contributors add @bunnysworld for code

**Pull request merged**
