### PR TITLE
Added script to visualize directory structure

### PR DESCRIPTION
**Pull request by dipanshparmar**
**script name** - tree.py

**Brief about script**
A script to visualize directory structure using Python

### Issue no.(must) - #489 

**Screenshots**
image
image

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between) (E.g. meet_schedular)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt (Include version numbers too e.g. pandas==0.0.1) with my script

### CODE REVIEW

**Comment by dipanshparmar** [comment]
@pawangeek I did add an issue number but it is not getting linked.

**Comment by pawangeek** [comment]
> @pawangeek I did add an issue number but it is not getting linked.

No issues, I done that

**Comment by dipanshparmar** [comment]
> > @pawangeek I did add an issue number but it is not getting linked.
> 
> No issues, I done that

Thank you :)

**Comment by dipanshparmar** [comment]
Hey, @pawangeek I guess I should not be asking this but can you please add my profile as well in the contributor's image section?

**Comment by pawangeek** [comment]
> Hey, @pawangeek I guess I should not be asking this but can you please add my profile as well in the contributor's image section?

Hey it's automated, you will be there from next day

**Comment by dipanshparmar** [comment]
> > Hey, @pawangeek I guess I should not be asking this but can you please add my profile as well in the contributor's image section?
> 
> Hey it's automated, you will be there from next day

Oh Okay! Thank you.

**Pull request merged**
