### PR TITLE
Created python script to download medium articles in PDF formats.

### PR DESCRIPTION
**Pull request by vivekascoder**
# Pull Request Template

**script name** -
medium-to-pdf/main.py

**Brief about script**
The script uses pdfkit module to fetch medium articles and cont=vert them in pdf files.

### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by vivekascoder** [comment]
Sir, I don't know why the first test is failing. Please take a look at PR sir.

**Comment by pawangeek** [comment]
Thanks, @vivekascoder for your, just one advice change -(dashes) to _(underscore) in folder name

**Comment by vivekascoder** [comment]
Thanks @pawangeek  for your review.

**Comment by vivekascoder** [comment]
@pawangeek , I changed the name.

**Comment by pawangeek** [comment]
Perfect @vivekascoder

**Comment by pawangeek** [comment]
@all-contributors add @vivekascoder for code

**Pull request merged**
