### PR TITLE
Python-music-downloader

### PR DESCRIPTION
**Pull request by siddharth1704**
# Pull Request Template

**script name** -
python music downloader

**Brief about script**
this script is used to download youtube videos using urls

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by siddharth1704** [comment]
#375

**Comment by siddharth1704** [comment]
#375 kindly look into the issue there

**Comment by pawangeek** [comment]
Check the tick box when completed

- [ ] Replace -(hyphen) with _(underscore) in folder name
- [ ] Add requirements.txt

**Comment by siddharth1704** [comment]
> Check the tick box when completed
> 
> * [X]  Replace -(hyphen) with _(underscore) in folder name
> * [X]  Add requirements.txt
done

**Comment by pawangeek** [comment]
@all-contributors add @siddharth1704 for code

**Pull request merged**
