### PR TITLE
CF Solution submit

### PR DESCRIPTION
**Pull request by Divyansh-20**
# Pull Request

**script name** - CF autosubmit

**Brief about script**

This script automates the process of problem submission on Codeforces. This has been made using Selenium Webdriver. All details regarding on script operations have been mentioned in depth in the README.md file

### Self Check

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

### CODE REVIEW

**Comment by pawangeek** [comment]
Hey, @Divyansh-20 your code seems fine, but is it possible to do that in a headless browser?

**Comment by Divyansh-20** [comment]
@pawangeek Yup, I understand your point, I'll try to come up with a solution to this.

**Comment by Divyansh-20** [comment]
@pawangeek We now have the headless version of this script, additionally it'll take a screenshot of the submission for reference as well.

**Comment by pawangeek** [comment]
Appreciable work @Divyansh-20 . You perfectly work on my point ✌

**Comment by pawangeek** [comment]
@all-contributors add @Divyansh-20 for code

**Pull request merged**
