### PR TITLE
WaterMark maker

### PR DESCRIPTION
**Pull request by m4dummies**
# Pull Request Template

**main.py** -

**The python script lets you add watermark to any pdf that you have.**

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

### CODE REVIEW

**Comment by m4dummies** [comment]
Hi can someone help me with this lint error. I tried running flake8 on the file i cant see any errors. I re-indented the whole file too.

Thank you

**Comment by Sacrezar** [comment]
Hey @m4dummies 

maybe try writing lines 8-12 like this:
```py
with open(pdf_file, "rb") as input_file,\
        open(watermark, "rb") as watermark_file:
    input_pdf = PdfFileReader(input_file)
    watermark_pdf = PdfFileReader(watermark_file)
    watermark_page = watermark_pdf.getPage(0)
```

**Comment by m4dummies** [comment]
> Hey @m4dummies
> 
> maybe try writing lines 8-12 like this:
> 
> ```python
> with open(pdf_file, "rb") as input_file,\
>         open(watermark, "rb") as watermark_file:
>     input_pdf = PdfFileReader(input_file)
>     watermark_pdf = PdfFileReader(watermark_file)
>     watermark_page = watermark_pdf.getPage(0)
> ```

Thanks mate. You have helped a lot.

**Comment by pawangeek** [comment]
@m4dummies script is  same as #243 and the requested changes too

**Comment by m4dummies** [comment]
> @m4dummies script is same as #243 and the requested changes too

Is there a change I need to do  ?

**Comment by pawangeek** [comment]
> In a nutshell, there should be a script to create that watermark pdf by python. Like adding the name in just single page PDF
> [#243 (comment)](https://github.com/python-geeks/Automation-scripts/pull/243#issuecomment-707456031)

Yes

**Comment by m4dummies** [comment]
> > In a nutshell, there should be a script to create that watermark pdf by python. Like adding the name in just single page PDF
> > [#243 (comment)](https://github.com/python-geeks/Automation-scripts/pull/243#issuecomment-707456031)
> 
> Yes

So the script will ask for a name that will be added as a watermarks, is that correct? 
My bad i thought we just need to add a watermark.

**Comment by pawangeek** [comment]
> > > In a nutshell, there should be a script to create that watermark pdf by python. Like adding the name in just single page PDF
> > > [#243 (comment)](https://github.com/python-geeks/Automation-scripts/pull/243#issuecomment-707456031)
> > 
> > 
> > Yes
> 
> So the script will ask for a name that will be added as a watermarks, is that correct?
> My bad i thought we just need to add a watermark.

Yes you got that point :)

**Comment by m4dummies** [comment]
> > > > In a nutshell, there should be a script to create that watermark pdf by python. Like adding the name in just single page PDF
> > > > [#243 (comment)](https://github.com/python-geeks/Automation-scripts/pull/243#issuecomment-707456031)
> > > 
> > > 
> > > Yes
> > 
> > 
> > So the script will ask for a name that will be added as a watermarks, is that correct?
> > My bad i thought we just need to add a watermark.
> 
> Yes you got that point :)

If possible can you not close this PR i will make a commit to the same PR in a while.

**Comment by m4dummies** [comment]
Also one more question...any specific font size that the text should be in the watermark ? @pawangeek

**Comment by pawangeek** [comment]
> If possible can you not close this PR I will make a commit to the same PR in a while.

Sure, I will not, just take your time, try to come up with a solution in the upcoming days. And ping me or Thomas for help

**Comment by m4dummies** [comment]
> > If possible can you not close this PR I will make a commit to the same PR in a while.
> 
> Sure, I will not, just take your time, try to come up with a solution in the upcoming days. And ping me or Thomas for help

Sure thanks. Also one more question...any specific font size that the text should be in the watermark ?

**Comment by pawangeek** [comment]
> Also one more question...any specific font size that the text should be in the watermark? @pawangeek

No that's not compulsory, any fixed font will solve the purpose too

**Comment by m4dummies** [comment]
> > Also one more question...any specific font size that the text should be in the watermark? @pawangeek
> 
> No that's not compulsory, any fixed font will solve the purpose too

Ok thanks. I will ping you once i have a solution

**Comment by pawangeek** [comment]
> Ok thanks. I will ping you once I have a solution

Just make sure It will not mix with the main text (like making it opaque or change its color to gray, etc.).

**Comment by m4dummies** [comment]
> > Ok thanks. I will ping you once I have a solution
> 
> Just make sure It will not mix with the main text (like making it opaque or change its color to gray, etc.).

Yup got it.

**Comment by m4dummies** [comment]
Hey @Sacrezar , I was successfully able to merge the pdfs. But the text overlaps. I am using reportlab, is there a way in which i can make the text transparent.

**Comment by m4dummies** [comment]
Hi @pawangeek , Now the script takes an input from the user asking for a text. It then adds that text as a watermark in the pdf file specified. Can you please check and let me know if this is the functionality you were looking for?

**Comment by pawangeek** [comment]
Add requirements.txt the script as mentioned in the checklist too

**Comment by m4dummies** [comment]
> Add requirements.txt with the script as mentioned in the checklist too

Oh right I might have missed it ill add it.

Also @pawangeek thank you for adding me to contributors. I wanted to ask if you could update it as the url doesnt lead to my profile and it doesnt show my name. 
Thanks

**Comment by m4dummies** [comment]
@pawangeek  I added the requirements.txt, please check.

**Comment by pawangeek** [comment]
> Also @pawangeek thank you for adding me to contributors. I wanted to ask if you could update it as the URL doesn't lead to my profile and it doesn't show my name.

That's because you changed your name from m4dummies to Neel Patel. I will try to fix that asap

**Comment by m4dummies** [comment]
> > Also @pawangeek thank you for adding me to contributors. I wanted to ask if you could update it as the URL doesn't lead to my profile and it doesn't show my name.
> 
> That's because you changed your name from m4dummies to Neel Patel. I will try to fix that asap

Yea, Thanks for looking in to.

**Comment by pawangeek** [comment]
And moreover is it possible for you to add any demo like watermark.pdf after formation. Or I will merge this?

**Comment by m4dummies** [comment]
Could u send me a pdf file that i can add a watermark to?

> And moreover is it possible for you to add any demo like watermark.pdf after formation. Or I will merge this?

**Comment by pawangeek** [comment]
[sample.pdf](https://github.com/python-geeks/Automation-scripts/files/5413889/sample.pdf)
Sure @m4dummies

**Comment by m4dummies** [comment]
Ok works I will add  it right now.

**Comment by m4dummies** [comment]
@pawangeek the images are too big in size. Should i still add it in the readme?

**Comment by m4dummies** [comment]
Hi @pawangeek can you check and see if you are able to see the images now ?

**Comment by pawangeek** [comment]
That's really awesome, neat, and perfect @m4dummies .

**Comment by pawangeek** [comment]
Change folder name to pdf_watermarkadder

**Comment by m4dummies** [comment]
Done @pawangeek Thanks.

**Comment by m4dummies** [comment]
@pawangeek Hi, can you please let me know once you change the name from the contributors list. Thank you

**Pull request merged**
