### PR TITLE
Added voice_to_text script

### PR DESCRIPTION
**Pull request by Crowfunder**
**script name** - voice_to_text

**Brief about script**
Transcribes speech from inputted audio file using PocketSphinx. May also output to a file.

### Issue no.(must) - #
#21 
### Self Check

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script.

### CODE REVIEW

**Comment by Crowfunder** [comment]
I have no idea what to do with flake8 lint. All the errors are caused by long lines and I'm pretty much unable to shorten them because they include descriptions for argparse arguments.

**Comment by bunnysworld** [comment]
hey @Crowfunder i think you must need  to short the help message  a bit or refrence this [E501](https://stackoverflow.com/questions/18685184/pep8-e501-line-too-long-error)

**Comment by Crowfunder** [comment]
Thanks for help @bunnysworld 
Passed all the linter check perfectly. 😄

**Comment by Crowfunder** [comment]
ZIP Password Cracker passwords.txt triggers SpellCheck.

> ./zip_password_cracker/passwords.txt:33: tigger ==> trigger
./zip_password_cracker/passwords.txt:1733: beng ==> being
./zip_password_cracker/passwords.txt:2599: bridget ==> bridged
./zip_password_cracker/passwords.txt:3076: technics ==> techniques
./zip_password_cracker/passwords.txt:3208: sting ==> string
./zip_password_cracker/passwords.txt:3236: microsof ==> microsoft
./zip_password_cracker/passwords.txt:3296: freee ==> free
./zip_password_cracker/passwords.txt:3347: guiness ==> guinness
./zip_password_cracker/passwords.txt:3401: amature ==> armature, amateur
./zip_password_cracker/passwords.txt:3822: litle ==> little
./zip_password_cracker/passwords.txt:3862: gallaries ==> galleries
./zip_password_cracker/passwords.txt:3945: absolut ==> absolute
./zip_password_cracker/passwords.txt:4171: buddah ==> buddha
./zip_password_cracker/passwords.txt:4438: japanes ==> japanese
./zip_password_cracker/passwords.txt:5098: chanel ==> channel
./zip_password_cracker/passwords.txt:5740: bizzare ==> bizarre
./zip_password_cracker/passwords.txt:6039: pasword ==> password
./zip_password_cracker/passwords.txt:6242: mone ==> mono, money
./zip_password_cracker/passwords.txt:6436: ceasar ==> caesar
./zip_password_cracker/passwords.txt:7714: strat ==> start, strata
./zip_password_cracker/passwords.txt:8181: wizzard ==> wizard
./zip_password_cracker/passwords.txt:8557: capetown ==> cape town
./zip_password_cracker/passwords.txt:8842: hart ==> heart, harm
./zip_password_cracker/passwords.txt:9365: gameboy ==> game boy
./zip_password_cracker/passwords.txt:9684: methos ==> methods, method

**Comment by bunnysworld** [comment]
hey @Crowfunder this ZIP Password Cracker passwords.txt triggers the same SpellCheck error while i was making my another PR 
i think there is some problem in zip_password_cracker/passwords.txt file which has been already merged by the admin don't worry this SpellCheck does not belongs to our personal PR's @pawangeek (mentioning you just to seek your attention for SpellCheck )

**Comment by pawangeek** [comment]
No need to worry @bunnysworld there is some spell check error in previous commit I will try to resolve it in a hour or so

**Comment by pawangeek** [comment]
Perfect @Crowfunder

**Comment by pawangeek** [comment]
@all-contributors add @Crowfunder for code

**Pull request merged**
