### PR TITLE
PDF Merger Script

### PR DESCRIPTION
**Pull request by paulopacitti**
# Pull Request Template

**script name** - PDF Merger

**What have you Changed**
- Added a _python_ script that can merge PDFs contained in a folder;
- Added `.DS_Store` files to be ignored in `.gitignore`;

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8. ~~(not 💯  well linted because ASCII art conflicts with [flake8's W605 rule](https://www.flake8rules.com/rules/W605.html))~~;
- [x] I have added README.md and `requirements.txt` with my script

### CODE REVIEW

**Comment by paulopacitti** [comment]
Should I remove the ASCII art to make `flake8` pipeline pass? :cry:

**Comment by paulopacitti** [comment]
ASCII art `flake8` lint issues fixed!

**Comment by pawangeek** [comment]
Buddy remove conflicts by deleting .gitignore file

**Comment by paulopacitti** [comment]
@pawangeek the `.gitignore` diff that I generated is important for [contributors that use **macOS**](https://www.jeffgeerling.com/blogs/jeff-geerling/stop-letting-dsstore-slow-you). Deleting this line `.gitignore` will pollute the repo with `.DS_Store` files. More than that, deleting the whole file will delete all `.gitignore` rules from the repo :/

**Comment by pawangeek** [comment]
@paulopacitti But I am unable to merge pull request till the conflict is not resolved

**Comment by paulopacitti** [comment]
@pawangeek I get it, but deleting the whole file doesn't help hahahaha I don't know how to solve complex conflicts in GitHub using forked branches, so let's do this way: 
1. I''ll restore `.gitignore` file the way it's in the `main` branch;
2. Maybe I open a an issue to add `.DS_Store` to `.gitignore` file;

**Comment by paulopacitti** [comment]
I was able to resolve the conflict! Now it's working!

**Comment by pawangeek** [comment]
Is it necessary to get names after putting them in a separate folder, instead, use os to get those files have .pdf extension and in the same folder?  

- [ ] Your script should able to merge all pdfs in the same dir without adding the name in the terminal
- [ ] And another thing is to use argparse (for getting path via the terminal in the same line) to make the process as smooth as possible for end-users

**Comment by paulopacitti** [comment]
> Is it necessary to get names after putting them in a separate folder

- The user needs to put all the files in the same folder and have a an alphabetically order, so it's merged in this order (it sorts the array of file names). The user only needs to input the path of the folder and enter the output file name. 

> instead, use os to get those files have .pdf extension and in the same folder?
- It's not required that the folder only contains `.pdf` files, look:
```python
pdfs_list = [file for file in os.listdir() if file.endswith(".pdf")]
```

>  And another thing is to use argparse (for getting path via the terminal in the same line) to make the process as smooth as possible for end-users

I made a _wizard-like_ script so it can have better UX (even with emojis and ASCII art hahahaha), so the user gets all the information needed running the script instead of reading the docs before running the script, like knowing the arguments to pass when the script is called

**Comment by pawangeek** [comment]
okay, thanks for clearing out my confusion :) and for your contribution

**Comment by pawangeek** [comment]
@all-contributors add @paulopacitti for code

**Pull request merged**
