### PR TITLE
Image Resizer

### PR DESCRIPTION
**Pull request by happyeric77**
# Pull Request Template

**image resizer** -

Added the script and added documentation with instructions. The script has been fully passed flake8 test.

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

### CODE REVIEW

**Comment by pawangeek** [comment]
Two small suggestion @happyeric77 

- [ ] Add error handling if someone tries to resize it into a bigger size
- [ ] Make script as smooth as possible for end-users means try to include "argparse" library which triggers from terminal no need to  put image path and name again and again in code

**Comment by happyeric77** [comment]
thanks for the suggestion @pawangeek 
Let me restructure and commit again.

**Comment by happyeric77** [comment]
**image resizer** -

Two updates as belew:
1. Add argparser for user to manipulate the function on console prompt. Also add the instruction into README.
2. Add the error handling to prevent user inputing the value larger than original size.

### Issue no.(#175) - #

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

**Comment by pawangeek** [comment]
Perfect @happyeric77

**Comment by pawangeek** [comment]
@all-contributors add @happyeric77 for code

**Pull request merged**
