### PR TITLE
Password Strength Checker

### PR DESCRIPTION
**Pull request by falguni-k**
**script name** - password_strength_checker.py

**What have you Changed**

added a new folder for Password Strength Checker. It contains a python script and a readme.md file.

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

### CODE REVIEW

**Comment by pawangeek** [comment]
Hey @falguni-k  Can you please enable linting in code? You can use this site http://pep8online.com/ to check your .py file.

**Comment by pawangeek** [comment]
Hey @falguni-k . Can you please enable linting in code? You can use this site http://pep8online.com/ to check your .py file.

**Comment by falguni-k** [comment]
Hi. I have enabled linting in the code and it has passed all the tests. You may merge now.

**Comment by pawangeek** [comment]
Thanks for that @falguni-k

**Comment by pawangeek** [comment]
@all-contributors please add @falguni-k  for code

**Pull request merged**
