### PR TITLE
Jarvis

### PR DESCRIPTION
**Pull request by anshul2807**
# Pull Request Template
##Issue no. - #398 

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
Fix lint

**Comment by anshul2807** [comment]
fixed with flake8.

**Comment by pawangeek** [comment]
Hey, @anshul2807 Just last one thing, change the folder name to 'jarvis_assistant'

**Comment by anshul2807** [comment]
> jarvis_assistant

Done.

**Comment by pawangeek** [comment]
@all-contributors add @anshul2807 for code

**Pull request merged**
