### PR TITLE
image to pdf

### PR DESCRIPTION
**Pull request by Prabesh-Shrestha**
# Pull Request Template

**script name** -

**Brief about script**
It converts images inside a folder("/images") to a pdf file 

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [ ] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between) (E.g. meet_schedular)
- [ ] I am following clean code and Documentation and my code is well linted with flake8.
- [ ] I have added README.md and requirements.txt (Include version numbers too e.g. pandas==0.0.1) with my script
- [ ] Just including required dependencies in requirements.txt (Don't include Python version too)

**If issue was not assigned to you Please don't make a PR. It will marked as invalid.**

### CODE REVIEW

**Comment by pawangeek** [comment]
Hey first a raise a issue of this

**Comment by Prabesh-Shrestha** [comment]
> Hey first a raise a issue of this

i have added the issue :)

**Comment by pawangeek** [comment]
> > Hey first a raise a issue of this
> 
> i have added the issue :)

now fix the linting errors

**Comment by Prabesh-Shrestha** [comment]
sorry for the linting error
its fixed now 
:D 

> > > Hey first a raise a issue of this
> > 
> > 
> > i have added the issue :)
> 
> now fix the linting errors

**Comment by pawangeek** [comment]
Now add README.md to brief describe the purpose, how to use, and you're done :)

**Comment by pawangeek** [comment]
That's neat now :)

**Comment by Prabesh-Shrestha** [comment]
thank you :)

**Pull request merged**
