### PR TITLE
Csolver

### PR DESCRIPTION
**Pull request by gkydev**
# Pull Request Template

**csolver.py** -

**Added captcha solver script**

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

### CODE REVIEW

**Comment by pawangeek** [comment]
Hey @gkydev. Can you please enable linting in code? You can use this site http://pep8online.com/ to check your .py file.

**Comment by gkydev** [comment]
Should be ok right now

**Comment by pawangeek** [comment]
Yes, it's fine now. Thanks for your contribution @gkydev. Leave a star to encourage me for creating more such tasks :)

**Comment by pawangeek** [comment]
@all-contributors please add @gkydev  for code

**Pull request merged**
