### PR TITLE
Price Tracker #397

### PR DESCRIPTION
**Pull request by chauhanarpit09**
# Pull Request Template

**Price Tracker** -

**Brief about script**

A Price Tracker will help you to track the price for all your favorite products and whenever the price drops down it will automatically send you an email

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
Fix lint

**Comment by chauhanarpit09** [comment]
fixed with flake8. check now!

**Comment by chauhanarpit09** [comment]
Now the issue is in the certificate generator script because of there code structure is not according to flake8
Screenshot (158)
According to flake8, all imports should be at the top but in the above code route imported at the bottom .. but if I have to change it to top the code will not run.
if I have to make it according to flake8. I have to make one file for the app i.e, paste all code of routes into init.py. 
Will I change it?

**Comment by pawangeek** [comment]
> Now the issue is in the certificate generator script because of there code structure is not according to flake8
> Screenshot (158)
> According to flake8, all imports should be at the top but in the above code route imported at the bottom .. but if I have to change it to top the code will not run.
> if I have to make it according to flake8. I have to make one file for the app i.e, paste all code of routes into init.py.
> shall I change it as it is **different script**?

Yeah @chauhanarpit09 , I know about it, there was one trailing space lint error in your last comment

**Comment by pawangeek** [comment]
@all-contributors add @chauhanarpit09 for code

**Comment by chauhanarpit09** [comment]
shall, I correct it according to flake8.

**Pull request merged**
