### PR TITLE
Automating the HR interview process

### PR DESCRIPTION
**Pull request by paridhi2105**
# Pull Request Template

**script name** - Automating the HR interview process

**Brief about script** - The program tries to automate the process of HR interview. It asks some relevant questions from the candidate and assigns a score out of 10. The score determines whether the person has passed the HR interview and be considered as a good fit for the company.

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
Hey few suggestions

- [ ] Check lint
- [ ] Make the folder name ('interview_automater')

**Comment by paridhi2105** [comment]
> Hey few suggestions
> * [x]  Check lint
> * [x]  Make the folder name ('interview_automater')

Thanks, I added the requirements.

**Comment by pawangeek** [comment]
> > Hey few suggestions
> > 
> > * [x]   Check lint
> > * [x]   Make the folder name ('interview_automater')
> 
> Thanks, I added the requirements.

- [ ] Linting
- [ ] Add requirments.txt file with versions

**Comment by paridhi2105** [comment]
> > > Hey few suggestions
> > > 
> > > * [x]    Check lint
> > > * [x]    Make the folder name ('interview_automater')
> > 
> > 
> > Thanks, I added the requirements.
> 
> * [x]  Linting
> * [x]  Add requirments.txt file with versions

Done the necessary, thanks.

**Comment by pawangeek** [comment]
@all-contributors add @paridhi2105 for code

**Pull request merged**
