### PR TITLE
Added script to generate passwords

### PR DESCRIPTION
**Pull request by dipanshparmar**
# Pull Request Template

**script name** - password_generator.py

**Brief about script**
A script to generate random passwords with the following criteria:

- Include symbols
- Include numbers
- Include lowercase characters
- Include uppercase characters
- exclude similar characters (optional)

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between) (E.g. meet_schedular)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt (Include version numbers too e.g. pandas==0.0.1) with my script

### CODE REVIEW

**Comment by dipanshparmar** [comment]
@pawangeek this PR is for Hacktoberfest. So please work with this accordingly.

**Comment by pawangeek** [comment]
Sure, but please add README.md and check the lint errors

**Comment by dipanshparmar** [comment]
You might have missed but the README is already there. And I didn't include the requirements.txt file as there are no dependencies that need to be explicitly installed.

**Comment by dipanshparmar** [comment]
And it seems like that the lint errors are coming from the auto_calendar folder. Please look into this. I double-checked my code with the online linter and the offline linter and there are no errors.
image

**Pull request merged**
