### PR TITLE
Add wifi_passwords script

### PR DESCRIPTION
**Pull request by Ajay-Raj-S**
### **wifi passwords** - script to list all connected wifi paswords.

This script requires python3 or above, it doesn't require any packages and environments, when running on Linux platform, it will require sudo password to list the password, windows doesn't ask for any admin password to list the wifi passwords, currently it only supports Linux and Windows.

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

### CODE REVIEW

**Comment by pawangeek** [comment]
I think it's only for Linux right?

**Comment by Ajay-Raj-S** [comment]
Hello @pawangeek  I have added support for both windows and linux platform in the code.

**Comment by Sacrezar** [comment]
As for me, I tried the windows version and i had to change utf-8 to ISO-8859-1
```python
list_ssids = [i.strip().lower() for i in wifi_ssids.stdout.decode("ISO-8859-1")\
.split('\r\n')]
```
and
```python
out = cat_cmd.stdout.decode("ISO-8859-1").split('\r\n')
```
It's probably because I have the french version and it has accents (I also need to change value in `startswith` to its french counterpart.


Here is your code for windows, french:
```python
import subprocess
import locale

default_lang = locale.getdefaultlocale()[0]

KEYWORDS = {
    "fr_FR": ["profil tous les utilisateurs", "Contenu"],
    "en_GB": ["all user profile", "Key Content"],
    "en_US": ["all user profile", "Key Content"]
}

wifi_ssids = subprocess.run(
    'netsh wlan show profile',
    capture_output=True,
    shell=True
)
list_ssids = [
    i.strip().lower() for i in wifi_ssids.stdout.decode("ISO-8859-1")
    .split('\r\n')
]

cmds = list()

for ssid in list_ssids:
    if ssid.startswith(KEYWORDS[default_lang][0]):
        cmds.append(ssid.split(':')[1].strip())

output = list()
for cmd in cmds:
    cat_cmd = f'netsh wlan show profile "{cmd}" key=clear'
    cat_cmd = subprocess.run(cat_cmd, capture_output=True, shell=True)
    out = cat_cmd.stdout.decode("ISO-8859-1").split('\r\n')
    for key in out:
        if key.strip().startswith(KEYWORDS[default_lang][1]):
            temp_key = key.split(': ')
            if len(temp_key) == 2:
                output.append((cmd, temp_key[1]))
                break
            else:
                output.append((cmd, ''))
                break

print('\n    List of Wifi SSIDs with passwords\n')
for i in output:
    print(f'\t{i[0]} : {i[1]}')

```

I don't think that changing utf-8 to ISO-8859-1 would cause any problem. But let me know if it works on EN Windows.

**Comment by Ajay-Raj-S** [comment]
> As for me, I tried the windows version and i had to change utf-8 to ISO-8859-1
> 
> ```python
> list_ssids = [i.strip().lower() for i in wifi_ssids.stdout.decode("ISO-8859-1")\
> .split('\r\n')]
> ```
> 
> and
> 
> ```python
> out = cat_cmd.stdout.decode("ISO-8859-1").split('\r\n')
> ```
> 
> It's probably because I have the french version and it has accents (I also need to change value in `startswith` to its french counterpart.
> 
> Here is your code for windows, french:
> 
> ```python
> import subprocess
> import locale
> 
> default_lang = locale.getdefaultlocale()[0]
> 
> KEYWORDS = {
>     "fr_FR": ["profil tous les utilisateurs", "Contenu"],
>     "en_GB": ["all user profile", "Key Content"],
>     "en_US": ["all user profile", "Key Content"]
> }
> 
> wifi_ssids = subprocess.run(
>     'netsh wlan show profile',
>     capture_output=True,
>     shell=True
> )
> list_ssids = [
>     i.strip().lower() for i in wifi_ssids.stdout.decode("ISO-8859-1")
>     .split('\r\n')
> ]
> 
> cmds = list()
> 
> for ssid in list_ssids:
>     if ssid.startswith(KEYWORDS[default_lang][0]):
>         cmds.append(ssid.split(':')[1].strip())
> 
> output = list()
> for cmd in cmds:
>     cat_cmd = f'netsh wlan show profile "{cmd}" key=clear'
>     cat_cmd = subprocess.run(cat_cmd, capture_output=True, shell=True)
>     out = cat_cmd.stdout.decode("ISO-8859-1").split('\r\n')
>     for key in out:
>         if key.strip().startswith(KEYWORDS[default_lang][1]):
>             temp_key = key.split(': ')
>             if len(temp_key) == 2:
>                 output.append((cmd, temp_key[1]))
>                 break
>             else:
>                 output.append((cmd, ''))
>                 break
> 
> print('\n    List of Wifi SSIDs with passwords\n')
> for i in output:
>     print(f'\t{i[0]} : {i[1]}')
> ```
> 
> I don't think that changing utf-8 to ISO-8859-1 would cause any problem. But let me know if it works on EN Windows.
> 
> Also, don't forget to pass checks

Thank you @Sacrezar , I will try with this on the windows.

**Comment by Ajay-Raj-S** [comment]
@Sacrezar I have updated the code accordingly for windows using locale, 
@pawangeek I will soon fix this Flake8linter issue too,

**Comment by Ajay-Raj-S** [comment]
@pawangeek All checks have successfully passed, please review and merge.
Thank you @Sacrezar for helping me update the code for localization.

**Comment by Sacrezar** [comment]
No problem, I'm glad it helped you 👍

**Comment by pawangeek** [comment]
@all-contributors add @Ajay-Raj-S for code

**Comment by Ajay-Raj-S** [comment]
Thank you @pawangeek

**Pull request merged**
