### PR TITLE
🆕 🆕Request to add New Script

### PR DESCRIPTION
**Pull request by Somanyu**
# Request to add New Python Script

**sys_info.py** -

**This python script basically tells you about various information about you system and CPU which you can use for troubleshooting. There is no need of requirements .txt because there is only one library to be installed and I have included in README.md**

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between) (E.g. meet_schedular)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt (Include version numbers too e.g. pandas==0.0.1) with my script
- [x] Just including required dependencies in requirements.txt (Don't include Python version too)

**If issue was not assigned to you Please don't make a PR. It will marked as invalid.**

### CODE REVIEW

**Comment by pawangeek** [comment]
Please raise a issue gorst, describing the motive in brief

**Comment by Somanyu** [comment]
Actually this is not a issue but adding new python script to the repository. I shouldn't have ticked issue. Apologies!

**Comment by pawangeek** [comment]
Yeah, you can but first create a new issue, and choose 'add a new script option' then just brief the purpose of this script

**Comment by Somanyu** [comment]
Okay I will open a new issue. Thanks

**Pull request merged**
