### PR TITLE
Password Manager Script

### PR DESCRIPTION
**Pull request by ebsa491**
# Pull Request Template

**script name** - Password Manager

**What have you Changed**

Just adding `password_manager/`, `password_manager/password_manager.py`, `password_manager/requirements.txt`
and `password_manager/README.md`

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
Hey, @ebsa491 Can you clean requirements.txt I think some of them are for linting purposes. Rest looks good

**Comment by ebsa491** [comment]
Sure, done!

**Comment by pawangeek** [comment]
That's fine now. Thanks for your contribution @ebsa491

**Comment by pawangeek** [comment]
@all-contributors add @ebsa491 for code

**Pull request merged**
