### PR TITLE
Add Currency Converter

### PR DESCRIPTION
**Pull request by maheshschand**
# Pull Request Template

**script name** - currency_converter.py

**What have you Changed**

Added a script to convert currency of one country to that of other country

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
Hey @maheshschand, Thanks for your contribution. Leave a star on the repo to encourage me more for creating such tasks :)

**Comment by maheshschand** [comment]
Thank you

**Comment by pawangeek** [comment]
@all-contributors please add @maheshschand for  code

**Comment by pawangeek** [comment]
@all-contributors please add @maheshschand  for code

**Pull request merged**
