### PR TITLE
Bookman

### PR DESCRIPTION
**Pull request by GoluffyxD**
# Pull Request Template

**script name** - Simple Book Manager
**BookMan**
**Brief about script** 
Create a DB to store which(name) book is placed with its path and subject of that book. Bonus if you able to add some kind of GUI to handle that.
A minimalist GUI application for managing books in local storage loaded with just enough features.

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by GoluffyxD** [comment]
@pawangeek How I would go about resolving the lint check fail?

**Comment by GoluffyxD** [comment]
@pawangeek Let me know if any improvements or features are needed. I'd appreciate any suggestions.

**Comment by pawangeek** [comment]
Can you please change the folder name to "book_manager"

**Comment by pawangeek** [comment]
Perfect @GoluffyxD

**Pull request merged**
