### PR TITLE
Mask Detection

### PR DESCRIPTION
**Pull request by anubhav201241**
# Pull Request Template

**script name** - mask_detection

**Brief about script**
Implement a Mask detector that accepts feed from the live camera that determines whether a person has to wear a mask or not. It will send alert audio if the person did not wear a mask using open cv, python, and deep learning

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between) (E.g. meet_schedular)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt (Include version numbers too e.g. pandas==0.0.1) with my script
- [x] Just including required dependencies in requirements.txt (Don't include Python version too)

### CODE REVIEW

**Comment by pawangeek** [comment]
Please fix the linting

**Comment by anubhav201241** [comment]
> Please fix the linting

I have fixed it but Did not know why the checks are failing

**Comment by pawangeek** [comment]
Duplicate of #216

**Comment by anubhav201241** [comment]
@pawangeek Can I work on another issue?

**Pull request closed without merging**
