### PR TITLE
Added the horoscope destination folder with 3 files.

### PR DESCRIPTION
**Pull request by kshittijagrawal**
# Pull Request Template

**Script Name** - horoscope destination

**Brief about script** - This script helps to let the user know about his/her **astro prediction**. The user only needs to know his/her zodiac sign and follow the steps as asked to. If followed correctly, the user gets to know the astro prediction for either yesterday, today or tomorrow completely based on the choice.

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between) (E.g. meet_schedular)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt (Include version numbers too e.g. pandas==0.0.1) with my script
- [ ] Just including required dependencies in requirements.txt (Don't include Python version too)

**If issue was not assigned to you Please don't make a PR. It will marked as invalid.**

### CODE REVIEW

**Comment by kshittijagrawal** [comment]
@pawangeek pls have a look and let me know if there's any change you need :)

**Comment by pawangeek** [comment]
Please fix the linting

**Comment by kshittijagrawal** [comment]
Hey @pawangeek !
Actually there was an error and I panicked and merged the upstream main into my local branch. I've therefore created a new branch with the pull request #602 . Kindly check it out. I've resolved all the previous issues as well.

**Comment by kshittijagrawal** [comment]
I'm sorry for the little misconfusion :(

**Pull request closed without merging**
