### PR TITLE
add: links extractor automation script

### PR DESCRIPTION
**Pull request by DevMahmoud10**
# Pull Request Template

**script name** -
links_extractor

**What have you Changed**
adding links extractor script

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
hey @DevMahmoud10 can you please enable linting in code (flake8 here)

**Comment by DevMahmoud10** [comment]
> hey @DevMahmoud10 can you please enable linting in code (flake8 here)

Done

**Comment by pawangeek** [comment]
Perfect @DevMahmoud10 Thanks for your valuable contribution

**Comment by pawangeek** [comment]
@all-contributors add @DevMahmoud10 for code

**Pull request merged**
