### PR TITLE
added pnr_status_checker

### PR DESCRIPTION
**Pull request by nikhilisaac**
# Pull Request Template

**script name** -pnr_status_checker

**Brief about script**
this is a python script to check the pnr status of travellers using the INDRAILWAY API

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between) (E.g. meet_schedular)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt (Include version numbers too e.g. pandas==0.0.1) with my script
- [x] Just including required dependencies in requirements.txt (Don't include Python version too)

### CODE REVIEW

**Comment by nikhilisaac** [comment]
i have to make changes for linti errors so do i make a new PR ?

**Comment by nikhilisaac** [comment]
could you guide me how to resolve the lint issues

**Comment by nikhilisaac** [comment]
@pawangeek will this solution work ?

**Comment by pawangeek** [comment]
> @pawangeek will this solution work ?

You should fix the linting errors first

**Comment by ujjwaltwitx** [comment]
use flake8 to fix the linting errors.

**Comment by nikhilisaac** [comment]
ill fix and open a new PR

**Pull request closed without merging**
