### PR TITLE
Changed PdfEncrypt to file_encrypter and updated documentation.

### PR DESCRIPTION
**Pull request by egurnick**
Changed PdfEncrypt to file_encrypter and updated documentation. The existing encrypter script can be used to encrypt any file, including images. Credit goes to SoumyaRanjanNaik, fa1l, and am401 for creating, fixing, and documenting the initial script.

# Pull Request Template

**script name** - file_encrypter

Encrypt or decrypt any file

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [ x My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
Sorry, but we won't allow any minor change in docs

**Comment by pawangeek** [comment]
Really, Sorry for that @egurnick

**Comment by pawangeek** [comment]
@all-contributors add @egurnick for code

**Comment by egurnick** [comment]
That is ok @pawangeek 
I am happy to contribute!

**Pull request merged**
