### PR TITLE
Added Sudoku Solver

### PR DESCRIPTION
**Pull request by jayaganeshkumar**
# Pull Request Template

**script name** - solve_sudoku.py

**What have you Changed**

what you changed in the codebase.write here

Added new folder named "Sudoku-Solver" with files: "README.md", "solve_sudoku.py".

### Self Check(Tick After Making pull Request)

- [X] This issue was assigned to me.
- [x] One Change in one Pull Request
- [X] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [X] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
Yeah, sure I will add that tag, but first, you should enable linting

**Comment by jayaganeshkumar** [comment]
How to do that? These lint errors are happening because of comments in the code.

**Comment by pawangeek** [comment]
@jayaganeshkumar Just put a space between # and rest comment

**Comment by jayaganeshkumar** [comment]
Can I edit the file in this PR only?? @pawangeek

**Comment by pawangeek** [comment]
Yes you can just go to file and click on 3 dots -> Edit this file and make changes or you can open a new issue if you're unable to do so

**Comment by pawangeek** [comment]
You can use this [site](http://pep8online.com/) to correct linting

**Comment by jayaganeshkumar** [comment]
@pawangeek  done! can you check it now?

**Comment by pawangeek** [comment]
Thanks for your contribution @jayaganeshkumar. Leave a star to encourage me for creating more such tasks :)

**Comment by jayaganeshkumar** [comment]
Thank you @pawangeek . Already starred the repo.

**Comment by pawangeek** [comment]
@all-contributors please add @jayaganeshkumar  for code

**Comment by pawangeek** [comment]
@all-contributors please add @jayaganeshkumar for code

**Comment by pawangeek** [comment]
@all-contributors please add @jayaganeshkumar for code

**Comment by maxily1** [comment]
Hey, The instructions in the README.md file are unclear.
Could you please clarify the instructions?
As of now I am getting such error:
```
Traceback (most recent call last):
  File "solve_sudoku.py", line 68, in <module>       
    solve_sudoku()  # calls the solve function       
  File "solve_sudoku.py", line 49, in solve_sudoku   
    if is_number_valid(row, col, n):
  File "solve_sudoku.py", line 10, in is_number_valid
    if grid[i][col] == num:
IndexError: list index out of range
```

**Comment by jayaganeshkumar** [comment]
@maxily1  you need to enter the board with 0s in place of empty places in the board

**Comment by pawangeek** [comment]
sol

I think it's working fine for me @maxily1 can you show me your logs

**Comment by jayaganeshkumar** [comment]
@pawangeek  yeah

**Comment by pawangeek** [comment]
And @maxily1  if you see any bug in the first run don't need to report here, you should open a new issue there is a template of the bug report, Reporting it here, send unwanted notifs to the author

**Pull request merged**
