### PR TITLE
Added file mover

### PR DESCRIPTION
**Pull request by Kirkkm**
I called my folder "filemover" in my pull request

# Pull Request Template

**script name** - filemover

**What have you Changed**

created a script filemover.py to move files from one folder to another, and created a README.md with instructions.

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
perfect @Kirkkm Thanks for your contribution

**Comment by pawangeek** [comment]
@all-contributor add @Kirkkm  for code

**Comment by Kirkkm** [comment]
@pawangeek No problem! It was a fun challenge to code.

**Comment by pawangeek** [comment]
@all-contributors add @Kirkkm for code

**Pull request merged**
