### PR TITLE
Image steganography

### PR DESCRIPTION
**Pull request by Sandhya1708**
# Pull Request Template

**script name** -

**Brief about script**

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
Few suggestions

- [ ] Elaborate README more
- [ ] Add requirements.txt file
- [ ] Add docstrings to function
- [ ] Linting

**Comment by pawangeek** [comment]
Hey Please check the requirements.txt of others or on web

**Comment by Sandhya1708** [comment]
Sorry about that. I have updated it

**Comment by pawangeek** [comment]
Clean the requirement.txt file, only add you're using in script not in whole environment

**Comment by pawangeek** [comment]
@all-contributors add @Sandhya1708 for code

**Pull request merged**
