### PR TITLE
Added a basic script for Youtube automation

### PR DESCRIPTION
**Pull request by suubh**
# Pull Request Template

**script name** -youtube.py

**What have you Changed**

what you changed in the codebase.write here
Modified my previous PR

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by suubh** [comment]
Still its happening even I tried yours one .

**Comment by suubh** [comment]
Its done ,you can merge now .
@pawangeek

**Comment by pawangeek** [comment]
Hey, @suubh just last thing your folder name should be in lowercase with space replaced by underscore

**Comment by suubh** [comment]
> 
> 
> Hey, @suubh just last thing space should be replaced by an underscore in your folder name

Done @pawangeek

**Comment by pawangeek** [comment]
@all-contributors please add @suubh  for code

**Pull request merged**
