### PR TITLE
Added Backup

### PR DESCRIPTION
**Pull request by TheFenrisLycaon**
**Auto_Backup**

**Takes automatic backups of a specified source path in zip format.**

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between) (E.g. meet_schedular)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt (Include version numbers too e.g. pandas==0.0.1) with my script
- [x] Just including required dependencies in requirements.txt (Don't include Python version too)

**If issue was not assigned to you Please don't make a PR. It will marked as invalid.**

### CODE REVIEW

**Comment by TheFenrisLycaon** [comment]
@pawangeek please check and merge.

**Comment by pawangeek** [comment]
Add the demo of backup to same folder of script, you're creating two folder in root, auto_backup, backup

**Comment by pawangeek** [comment]
Perfect :)

**Comment by TheFenrisLycaon** [comment]
Can you merge it and mark as accepted?

**Pull request merged**
