### PR TITLE
Adding To-Do List Application

### PR DESCRIPTION
**Pull request by aayuv17**
# Pull Request Template

**script name** - To-Do List Application

**What have you Changed**
Added a todo list application made using Python's flask framework

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

### CODE REVIEW

**Comment by pawangeek** [comment]
Hey @aayuv17. Can you please enable linting in code? You can use this site http://pep8online.com/ to check your .py file.

**Comment by aayuv17** [comment]
Hey, so I have performed linting on the python code...just wanted to point out that the site you recommended and the tool being used for checking are following different rules in some cases so I installed the flake8 module and used that. Maybe if others face issues with the site you can tell them to do the same.

**Comment by pawangeek** [comment]
Thanks for your contribution and valuable advice @aayuv17. Leave a star on the repo to encourage me for creating more such tasks :)

**Comment by pawangeek** [comment]
@all-contributors please add @aayuv17  for code

**Pull request merged**
