### PR TITLE
added scraper

### PR DESCRIPTION
**Pull request by Sripaad**
**script name** - google images scraper

**Brief about script**
Automation script with a cli, that image scrapes a given keyword.

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

### CODE REVIEW

**Comment by Sacrezar** [comment]
Hi,

do you really need all these import in your requirements.txt?
As far I see, you just use Selenium, BeautifulSoup4, requests and driver_downloader

**Comment by Sripaad** [comment]
@Sacrezar i just created the requirements.txt file using the pip freeze command.

**Comment by Sacrezar** [comment]
> 
> 
> @Sacrezar i just created the requirements.txt file using the pip freeze command.

Oh, so I think I know why there is so many packages. 
`pip freeze` creates a listing of all your installed packages.

It would have been interesting to do so if you had created a venv because in this venv you would have only imported packages that you need (Selenium, BeautifulSoup4, requests probably).

Let me just review your code, i'll tell you what to change 😃

**Comment by Sripaad** [comment]
> > @Sacrezar i just created the requirements.txt file using the pip freeze command.
> 
> Oh, so I think I know why there is so many packages.
> `pip freeze` creates a listing of all your installed packages.
> 
> It would have been interesting to do so if you had created a venv because in this venv you would have only imported packages that you need (Selenium, BeautifulSoup4, requests probably).
> 
> Let me just review your code, i'll tell you what to change

ohhh alright ill change it up then.

**Review by Sacrezar — CHANGES_REQUESTED** [review]
* driver_downloader will work only for Linux users. It is not a problem, either make it work for windows or precise that the windows user must install and change the path
* `/usr/bin/geckodriver` will work only for Linux users, make it an hardcoded path that the user can change, like `GECKO_PATH`
* There is a missing "--" at line 25 `"--image_count"`

It "works" (it download pics) but I don't know why, when I choose to pick 10 pic, I get twenty and it crashs at line 84
image
image

for the requirements, 
```
bs4
selenium
requests
urllib3
```
will be enough I think.

I don't have a linux machine right now so I can't try on it

**Comment by Sripaad** [comment]
> * driver_downloader will work only for Linux users. It is not a problem, either make it work for windows or precise that the windows user must install and change the path
> * `/usr/bin/geckodriver` will work only for Linux users, make it an hardcoded path that the user can change, like `GECKO_PATH`
> * There is a missing "--" at line 25 `"--image_count"`
> 
> It "works" (it download pics) but I don't know why, when I choose to pick, like, 10 pic, I get twenty and it crashs at line 84
> image
> image
> 
> for the requirements,
> 
> ```
> bs4
> selenium
> requests
> urllib3
> ```
> 
> will be enough I think.
> 
> I don't have a linux machine right now so I can't try on it

Oh yeah idk how to make it work for windows users actually, ive been thinking about it but idk enough about how windows works to actually change my code, sure ill add $GECKO_PATH that makes sense. Can you try running driver_downloader in PowerShell, from my very limited use of windows i've heard few linux commands do work there. Ill send a fix for the message not found.

**Comment by Sacrezar** [comment]
It's understandable if you are not familiar with Windows. 

On powershell, I think it would be this 👇 to download and unzip.
```ps1
$url = "https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-win64.zip"
$out = "C:\Users\user1\Desktop\geckodriver.zip"
wget  -Uri $url  -OutFile $out
Expand-Archive -LiteralPath $out
```
wget is an alias of `Invoke-WebRequest` so you can use but the command you actually use is `Invoke-WebRequest`. In fact I think that all the UNIX command you can use are actually aliases of ps commands. `ls` for example:
image

Your script is actually working on Windows, It downloads and put all pic in a folder but it crashs after 😅

**Comment by Sripaad** [comment]
@Sacrezar  This should work on both, try it.

**Review by Sacrezar — CHANGES_REQUESTED** [review]
As for the scrapping it is working fine. I think it is also working as for the geckodriver installer.
Just don't forget to cast count into a string at line 82.

And when I talked about `GECKO_PATH`, I meant it like a global variable you could call like that: 
```py
GECKO_PATH = "your/path/geckodriver.exe"
def your_func():
    if os.path.isfile(GECKO_PATH):
```
Just do these two things and we're OK 😃 

Thank you for your work 👍

**Comment by Sripaad** [comment]
@Sacrezar oh damn idk how i missed that one on line 82, thanks for pointing it out. Here are the changes

**Review by Sacrezar — APPROVED** [review]
No worries 😃 
I'll let @pawangeek merge this PR.

**Comment by pawangeek** [comment]
@all-contributors add @Sripaad for code

**Pull request merged**
