### PR TITLE
Automated voice prescription generator

### PR DESCRIPTION
**Pull request by sandipan898**
# Pull Request Template

**Automated voice prescription generator** - 

**Generates Prescriptions in the form of PDF Files by recognizing the voice inputs. When the main code being executed, information are to be given by following the instructions.** 

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
Fix linting issues, and rename folder to just 'prescription_generator'

**Comment by sandipan898** [comment]
@pawangeek please check and let me know if any changes needed.

**Comment by pawangeek** [comment]
Sandeep see the [file changes](https://github.com/python-geeks/Automation-scripts/pull/368/files) tab, Just make changes in by adding your folder, If you're messed with something, clone the repo again and add your folder

**Comment by sandipan898** [comment]
@pawangeek What things need to be changed? can you please guide me a bit so that I can do the needful.

**Comment by pawangeek** [comment]
> @pawangeek What things need to be changed? can you please guide me a bit so that I can do the needful.
> Else can make another pull request addressing the same issue?

Yup create a new PR, that's better

**Comment by sandipan898** [comment]
One thing to clarify, do I need to fork it again or I can just clone my already forked repo and make changes again?
As this is my first ever contribution I'm facing a little bit problem managing it, so any kind of guidance will be grateful for me.

**Comment by pawangeek** [comment]
I recommend to fork it again

**Comment by sandipan898** [comment]
I've created a fresh pull request. Please check it here #384

**Pull request closed without merging**
