### PR TITLE
Auto Backup

### PR DESCRIPTION
**Pull request by TheFenrisLycaon**
# Auto_Backup

Takes automatic backups of a specified source path in zip format.

### Issue no.(must) - #495 

- [x ] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between) (E.g. meet_schedular)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [ ] I have added README.md and requirements.txt (Include version numbers too e.g. pandas==0.0.1) with my script
- [ ] Just including required dependencies in requirements.txt (Don't include Python version too)

### CODE REVIEW

**Comment by pawangeek** [comment]
Hey @TheFenrisLycaon create two separate PRs for two issue

**Comment by TheFenrisLycaon** [comment]
My bad.

**Comment by TheFenrisLycaon** [comment]
Can you delete this one?

**Comment by pawangeek** [comment]
Closing it, create new PR

**Pull request closed without merging**
