### PR TITLE
Added : QR Code Scanner

### PR DESCRIPTION
**Pull request by rkgeekoftheweek**
**script name** - QR Code Scanner

**What have you Changed**

Added python code for QR code Scanner

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
Hey you can use http://pep8online.com/ for removing linting errors

**Comment by rkgeekoftheweek** [comment]
> Hey you can use this [site](http://pep8online.com/) for removing linting errors

ok , let me check that

**Comment by pawangeek** [comment]
Hey, those errors associated with .py file. That's showing error in your complete PR not in README

**Comment by rkgeekoftheweek** [comment]
@pawangeek , Code is working fine and I followed the mentioned website too. I am not sure where these lint errors are coming from . Can you please help me with this?

**Comment by Sacrezar** [comment]
@rkgeekoftheweek Hi, this repo use the Flake8 linting, 
just try : 
`pip install flake8`
and then
`py -m flake8 filename.py`
It will show you what you have to correct, like this
image

**Comment by rkgeekoftheweek** [comment]
> @rkgeekoftheweek Hi, this repo uses the Flake8 linting,
> just try :
> `pip install flake8`
> and then
> `py -m flake8 filename.py`
> It will show you what you have to correct, like this
> image
> 
> You can also check these errors there https://github.com/python-geeks/Automation-scripts/pull/42/checks

Thanks man !

**Comment by pawangeek** [comment]
Thanks for your contribution @rkgeekoftheweek. Leave a star to encourage me for creating more such tasks :)

**Comment by pawangeek** [comment]
@all-contributors please add @rkgeekoftheweek  for  code

**Comment by pawangeek** [comment]
@all-contributors please add @rkgeekoftheweek for code

**Pull request merged**
