### PR TITLE
Setup virtual environment

### PR DESCRIPTION
**Pull request by fa1l**
# Pull Request Template

**script name** all

**What have you Changed**
* added makefile for setup virtual environment
* update all readmes
* add missing requirements in some projects
* add .gitignore

what you changed in the codebase.write here

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
Hey you're not allowed to add that makefile in other's script folders

**Comment by fa1l** [comment]
I thought that separate virtualenvs for every automation tool is better. Because some tools may depend on the same library but with different versions. Trying to merge it in one venv will be a huge pain.

**Comment by pawangeek** [comment]
Hey, I think there are conflicts in multiple folders. Please check that out

**Comment by fa1l** [comment]
> Hey, I think there are conflicts in multiple folders. Please check that out

Yep, sure, I'll fix it ASAP

**Comment by pawangeek** [comment]
@all-contributors add @fa1l for code and infrastructure

**Comment by pawangeek** [comment]
Good work @fa1l I will reference this issue multiple times in further :)

**Pull request merged**
