### PR TITLE
Google Meet Joiner

### PR DESCRIPTION
**Pull request by m4dummies**
# Google meet joiner

**main.py** -

**python script built to join google meet classes automatically **

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

Thank you

### CODE REVIEW

**Comment by m4dummies** [comment]
Hello, 
what was the error here?

**Comment by Sacrezar** [comment]
Hey,

try installing flake8 and then run it on your py file, it will show you what is wrong.
```bash
py -m pip install flake8
py -m flake8 main.py
```

Alternatively, you can go to https://github.com/python-geeks/Automation-scripts/pull/302/checks?check_run_id=1274832343

**Comment by m4dummies** [comment]
> Hey,
> 
> try installing flake8 and then run it on your py file, it will show you what is wrong.
> 
> ```shell
> py -m pip install flake8
> py -m flake8 main.py
> ```
> 
> Alternatively, you can go to https://github.com/python-geeks/Automation-scripts/pull/302/checks?check_run_id=1274832343

I mean i checked the page u linked. But it just say failed after x number of seconds. It is not showing what the issue is.

**Comment by m4dummies** [comment]
> Hey,
> 
> try installing flake8 and then run it on your py file, it will show you what is wrong.
> 
> ```shell
> py -m pip install flake8
> py -m flake8 main.py
> ```
> 
> Alternatively, you can go to https://github.com/python-geeks/Automation-scripts/pull/302/checks?check_run_id=1274832343


Also i installed flake8 and ran it on my file.
No error showed up, all that came up was this `indentation contains tabs`

**Comment by Sacrezar** [comment]
Did you see this?
image
for example, on line 9 it must be a blank line in order to have 2 blank lines between whatever you wrote and your function

With this code, I have no linting error:

```python

import time
import webbrowser
import schedule
import pyautogui

url1 = "https://meet.google.com/"
url2 = "https://www.google.com/"


def class1():
    webbrowser.open(url1)
    time.sleep(3)
    print("Joining Class")
    time.sleep(2)
    pyautogui.hotkey('command', 'd')
    print("turned off camera")
    time.sleep(2)
    pyautogui.hotkey('command', 'e')
    print("turned off mic")
    time.sleep(3)

    for i in range(4):
        pyautogui.press('tab')

    time.sleep(3)
    pyautogui.press('enter')


def class2():
    webbrowser.open(url2)
    time.sleep(3)
    print("Joining Class")
    time.sleep(2)
    pyautogui.hotkey('command', 'd')
    print("turned off camera")
    time.sleep(2)
    pyautogui.hotkey('command', 'e')
    print("turned off mic")
    time.sleep(3)

    for i in range(4):
        pyautogui.press('tab')

    time.sleep(3)
    pyautogui.press('enter')


if __name__ == "__main__":
    schedule.every().day.at("16:37").do(class1)
    schedule.every().day.at("14:00").do(class2)

    while True:
        schedule.run_pending()  # check if we need to run anything
        time.sleep(10)  # wait 10 seconds before checking each time again
```

See: https://www.flake8rules.com/rules/E101.html and https://www.flake8rules.com/rules/W191.html

Out of curiosity, which IDE do you use?

**Comment by Sacrezar** [comment]
Flake8 is a tool that will check your code syntax and provide instructions on how to clean it. So yeah even you don't pass Flake8, your code can run well

It allows us to have a certain consistency on all these scripts, that's why we have a check 😉

**Comment by m4dummies** [comment]
> Did you see this?
> image
> for example, on line 9 it must be a blank line in order to have 2 blank lines between whatever you wrote and your function
> 
> With this code, I have no linting error:
> 
> ```python
> import time
> import webbrowser
> import schedule
> import pyautogui
> 
> url1 = "https://meet.google.com/"
> url2 = "https://www.google.com/"
> 
> 
> def class1():
>     webbrowser.open(url1)
>     time.sleep(3)
>     print("Joining Class")
>     time.sleep(2)
>     pyautogui.hotkey('command', 'd')
>     print("turned off camera")
>     time.sleep(2)
>     pyautogui.hotkey('command', 'e')
>     print("turned off mic")
>     time.sleep(3)
> 
>     for i in range(4):
>         pyautogui.press('tab')
> 
>     time.sleep(3)
>     pyautogui.press('enter')
> 
> 
> def class2():
>     webbrowser.open(url2)
>     time.sleep(3)
>     print("Joining Class")
>     time.sleep(2)
>     pyautogui.hotkey('command', 'd')
>     print("turned off camera")
>     time.sleep(2)
>     pyautogui.hotkey('command', 'e')
>     print("turned off mic")
>     time.sleep(3)
> 
>     for i in range(4):
>         pyautogui.press('tab')
> 
>     time.sleep(3)
>     pyautogui.press('enter')
> 
> 
> if __name__ == "__main__":
>     schedule.every().day.at("16:37").do(class1)
>     schedule.every().day.at("14:00").do(class2)
> 
>     while True:
>         schedule.run_pending()  # check if we need to run anything
>         time.sleep(10)  # wait 10 seconds before checking each time again
> ```
> 
> See: https://www.flake8rules.com/rules/E101.html and https://www.flake8rules.com/rules/W191.html
> 
> Out of curiosity, which IDE do you use?


I am using sublime text at the moment. 
So if i fix the spaces and indentation, where it says its a mix of spaces and tabs. So if make another PR will it clear?

**Comment by Sacrezar** [comment]
Yes but you don't need to open another PR, you just have to commit your changes on the same branch you did the PR ( ` googlemeet-joiner`)

It will automatically update the PR

**Comment by m4dummies** [comment]
> Yes but you don't need to open another PR, you just have to commit your changes on the same branch you did the PR ( ` googlemeet-joiner`)
> 
> It will automatically update the PR

**Comment by m4dummies** [comment]
> Yes but you don't need to open another PR, you just have to commit your changes on the same branch you did the PR ( ` googlemeet-joiner`)
> 
> It will automatically update the PR

Alright got it. Thanks for your help.

**Comment by Sacrezar** [comment]
Okay I found why you got these errors.

I use vscode, and the indent is automatically done with spaces rather than tab.
image

It seems that Sublime text default is using tab 
image
image

**Comment by m4dummies** [comment]
> Okay I found why you got these errors.
> 
> I use vscode, and the indent is automatically done with spaces rather than tab.
> image
> 
> It seems that Sublime text default is to use tab
> image
> image

Oh, now i get it. Thanks a lot for your help. I appreciate it.

**Comment by m4dummies** [comment]
My tab width size is 4 in sublime as well. I tried writing the program in vsc but got the same error. I don't know where the lint error comes in. @Sacrezar

**Comment by Sacrezar** [comment]
> 
> 
> My tab width size is 4 in sublime as well. I tried writing the program in vsc but got the same error. I don't know where the lint error comes in. @Sacrezar

I just checked, you corrected these lint error. Good work 😉 

Your errors are different now:
image
for your second function you wrote `class1` instead of `class2`

and you have to add somes spaces when you use inline comment.

Something like that should work:
```python
if __name__ == "__main__":
    schedule.every().day.at("16:00").do(class1)
    schedule.every().day.at("06:00").do(class2)

    while True:
        schedule.run_pending()  # check if we need to run anything
        time.sleep(10)  # wait 10 second before checking again

```

**Review by Sacrezar — CHANGES_REQUESTED** [review]
- [ ] Correct Lint errors
image
- [ ] Delete one of the function since they are the same and use the url as an arg 
```python
def attend_my_class(url):
    webbrowser.open(url)
    ...
    ...


if __name__ == "__main__":
    schedule.every().day.at("16:00").do(attend_my_class(url1))
    schedule.every().day.at("06:00").do(attend_my_class(url2))
    ....
```

If you want, you can even allow the user to put the link when launching the script. See sys.argv [here](https://docs.python.org/3/library/sys.html#sys.argv) and [there](https://www.geeksforgeeks.org/how-to-use-sys-argv-in-python/). That's not an obligation 😃

**Comment by m4dummies** [comment]
Hey @Sacrezar , I ran the flake8 on the file again and there are not lint errors anymore. 
I will make sure to add argvs and remove class1 and class2.

**Comment by m4dummies** [comment]
> * [ ]  Correct Lint errors
>   image
> * [ ]  Delete one of the function since they are the same and use the url as an arg
> 
> ```python
> def attend_my_class(url):
>     webbrowser.open(url)
>     ...
>     ...
> 
> 
> if __name__ == "__main__":
>     schedule.every().day.at("16:00").do(attend_my_class(url1))
>     schedule.every().day.at("06:00").do(attend_my_class(url2))
>     ...
> ```
> 
> If you want, you can even allow the user to put the link when launching the script. See sys.argv [here](https://docs.python.org/3/library/sys.html#sys.argv) and [there](https://www.geeksforgeeks.org/how-to-use-sys-argv-in-python/). That's not an obligation 😃

 Hi again. I added the changes to my script. Where do i check the boxes for the changes that were assigned to me?

**Review by Sacrezar — APPROVED** [review]
Nice work! 👍

**Comment by m4dummies** [comment]
> Nice work! 👍

Thank you.
Thanks for all your help too.

**Comment by pawangeek** [comment]
@all-contributors add @m4dummies for code

**Pull request merged**
