### PR TITLE
Adding covid-19 tracker

### PR DESCRIPTION
**Pull request by edoardottt**
# Pull Request Template

**Covid-19** -

**What have you Changed**

Added scripts to retriving current data about Covid-19

I know you will mark this as unvalid, but maybe could be useful.

### CODE REVIEW

**Comment by pawangeek** [comment]
okay, that's fine, but please check linting (flake8 here)

**Comment by edoardottt** [comment]
Update

**Comment by pawangeek** [comment]
Hey, thanks for your contribution. Leave a star ⭐ if you enjoy this :)

**Comment by pawangeek** [comment]
@all-contributors please add @edoardottt  for code

**Pull request merged**
