### PR TITLE
Added Website Blocker Script

### PR DESCRIPTION
**Pull request by GaganSingh5**
**Website Blocker** -

**Added the script for website blocker**

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

### CODE REVIEW

**Comment by pawangeek** [comment]
Hey, is it possible to add an unblocking script too ??

**Comment by GaganSingh5** [comment]
hey @pawangeek the works in such a way that when you exit from the script it automatically restore the changes

**Comment by pawangeek** [comment]
Ahh okay, I don't go through that README, sorry for that

**Comment by GaganSingh5** [comment]
let me clear one this if the script closes unexpectedly or force close than the changes will not restore
restore function only works if you close the script with a given Blocker Menu Interface

**Comment by pawangeek** [comment]
oh, please Include this info in README a make a new PR for that asap

**Pull request merged**
