### PR TITLE
Competitive Calendar

### PR DESCRIPTION
**Pull request by SakshiUppoor**
# Pull Request Template

**script name** - competitive_calendar

**What have you Changed**

Added a script to display list of ongoing and future competitive contests.

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
Perfect @SakshiUppoor. Just two small suggestions

- [ ] Remove .gitignore file
- [ ] Add all supported sites in README (Like API fetch details from which contest sites)

**Comment by SakshiUppoor** [comment]
Made the requested changes

**Comment by pawangeek** [comment]
Well done, @SakshiUppoor

**Comment by pawangeek** [comment]
@all-contributors add @SakshiUppoor for code

**Comment by SakshiUppoor** [comment]
Thank you so much! It was a great learning experience! 😃

**Pull request merged**
