### PR TITLE
Sending SMS

### PR DESCRIPTION
**Pull request by YourFriendlyError**
Added script for sending sms, README and requirements.txt

# Pull Request Template

**script name** -
sms.py

**What have you Changed**
New script, README, and requirements.txt

what you changed in the codebase.write here
New Script, README, and requirements.txt

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
Hey, @YourFriendlyError. Thanks for your contribution. Leave a star to encourage me more for creating such tasks :)

**Comment by pawangeek** [comment]
@all-contributors please add @YourFriendlyError   for  code

**Comment by pawangeek** [comment]
@all-contributors please add @YourFriendlyError for code

**Comment by YourFriendlyError** [comment]
> Hey, @YourFriendlyError. Thanks for your contribution. Leave a star to encourage me more for creating such tasks :)

Thanks!

**Pull request merged**
