### PR TITLE
PDF Encryption and Decryption Scripts (using AES)

### PR DESCRIPTION
**Pull request by SoumyaRanjanNaik**
# Pull Request Template

**script name** 
- pdf_encrypt/PdfEncrypt.py
- pdf_encrypt/PdfDecrypt.py

**What have you Changed**

- Added a Script for encryption of PDF files
- Added a Script for Decryption of encrypted PDF files

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

### CODE REVIEW

**Comment by pawangeek** [comment]
Hey @SoumyaRanjanNaik can you add some kind of password strength checker while encrypting (like have more than 8 chars, digit + special char  + uppercase is a  must. You can take help from #47 

- [ ] Password should be >= 8 chars
- [ ] Including special char, digit, uppercase is must

**Comment by SoumyaRanjanNaik** [comment]
Okay I will integrate it. Give me some time.

**Comment by pawangeek** [comment]
Sure :)

**Comment by pawangeek** [comment]
That's awesome @SoumyaRanjanNaik :)

**Pull request merged**
