### PR TITLE
programming_quoter by using win10toast

### PR DESCRIPTION
**Pull request by ShubhamNagure**
# Pull Request Template

**script name** - programming_quoter

**Brief about script**
- A python script that displays a programming quote as toast notifs on running a script.

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If the issue was not assigned to you Please don't make a PR. It will mark as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
Hey @ShubhamNagure how do it will show Programming Quotes can you highlight that line?

**Comment by ShubhamNagure** [comment]
> Hey @ShubhamNagure how do it will show Programming Quotes can you highlight that line?

Hi @pawangeek ,

```
toaster.show_toast("**Example One:",
                   "This is first notifs.**",
                   icon_path=None,
                   duration=10)
```

As you can see in the bold parameter of the "show_toast()" method, there we can put "Quotes" so to speak " Programming quotes".

> At first glance, I understood that you need a script in which a notification should pop up with some sort of "quotes". Please correct me if this is not what you want.

**Comment by pawangeek** [comment]
> > Hey @ShubhamNagure how do it will show Programming Quotes can you highlight that line?
> 
> Hi @pawangeek ,
> 
> ```
> toaster.show_toast("Here you put programmiing quotes.",
>                    icon_path=None,
>                    duration=10)
> ```
> 
> As you can see in the bold parameter of the "show_toast()" method, there we can put "Quotes" so to speak " Programming quotes".
> 
> > At first glance, I understood that you need a script in which a notification should pop up with some sort of "quotes". Please correct me if this is not what you want.

Hey @ShubhamNagure okay that's cool. But can you instead add some programming quotes to the list (At least 15) and randomly get that

**Comment by ShubhamNagure** [comment]
> > > Hey @ShubhamNagure how do it will show Programming Quotes can you highlight that line?
> > 
> > 
> > Hi @pawangeek ,
> > ```
> > toaster.show_toast("Here you put programmiing quotes.",
> >                    icon_path=None,
> >                    duration=10)
> > ```
> > 
> > 
> > As you can see in the bold parameter of the "show_toast()" method, there we can put "Quotes" so to speak " Programming quotes".
> > > At first glance, I understood that you need a script in which a notification should pop up with some sort of "quotes". Please correct me if this is not what you want.
> 
> Hey @ShubhamNagure okay that's cool. But can you instead add some programming quotes to the list (At least 15) and randomly get that

Hey @pawangeek DONE #294 . Added some cool programming quotes and displayed them randomly in the notification. Please review and suggest if there is anything else left to add.
Thank you.

**Comment by pawangeek** [comment]
FIne now @ShubhamNagure

**Comment by pawangeek** [comment]
@all-contributors add @ShubhamNagure for code

**Pull request merged**
