### PR TITLE
Added TweetBot to the repo

### PR DESCRIPTION
**Pull request by ashkankamyab**
# Pull Request Template

**script name** -

**What have you Changed**

what you changed in the codebase.write here

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by ashkankamyab** [comment]
@pawangeek 
May you please give me a hint to find the correct linter for vscode ?!
I used to use PEP-8. So this time I don't want to lint it manually 🤯

**Review by pawangeek — CHANGES_REQUESTED** [review]
Can you please add docstrings with class and functions including parameter and working. It's good for testing and end to end users

**Comment by pawangeek** [comment]
That's awesome @ashkankamyab 

> @pawangeek
> May you please give me a hint to find the correct linter for vscode ?!
> I used to use PEP-8. So this time I don't want to lint it manually 🤯

You should user flake8 for this

**Comment by ashkankamyab** [comment]
> Can you please add docstrings with class and functions including parameter and working. It's good for testing and end to end users

Well I am comfort using class 🙈 But if you explain more. I can give it a try.

**Comment by pawangeek** [comment]
> > Can you please add docstrings with class and functions including parameter and working. It's good for testing and end to end users
> 
> Well I am not comfort using class 🙈 But if you explain more I can give it a try.

Then just do that with functions. Just add what's the purpose and params at the top of functions using docstring (""" """)

**Comment by ashkankamyab** [comment]
> That's awesome @ashkankamyab
> 
> > @pawangeek
> > May you please give me a hint to find the correct linter for vscode ?!
> > I used to use PEP-8. So this time I don't want to lint it manually 🤯
> 
> You should user flake8 for this

is [this](https://github.com/kevinglasson/vscode-cornflakes-linter) approved?

**Comment by ashkankamyab** [comment]
> > > Can you please add docstrings with class and functions including parameter and working. It's good for testing and end to end users
> > 
> > 
> > Well I am not comfort using class 🙈 But if you explain more I can give it a try.
> 
> Then just do that with functions. Just add what's the purpose and params at the top of functions using docstring (""" """)

Ahh, That's you mean. Ok! I will why not !

**Review by pawangeek — COMMENTED** [review]
Perfect. Thanks for your contribution @ashkankamyab

**Review by pawangeek — APPROVED** [review]

**Comment by ashkankamyab** [comment]
> Perfect. Thanks for your contribution @ashkankamyab

Don't mention it 🍻 . See you in next PR 👍

**Comment by pawangeek** [comment]
@all-contributors please add @ashkankamyab for code

**Pull request merged**
