### PR TITLE
Dup file finder

### PR DESCRIPTION
**Pull request by varuntumbe**
# Pull Request Template

Duplicate File Checker

**What have you Changed**

I have created one python file which detects duplicate files and one readme file

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
Can you enable linting (flake8) in .py file

**Comment by varuntumbe** [comment]
Yeah sure. I guess pylint was there in vscode as default

**Comment by varuntumbe** [comment]
I have installed flake 8 and modified according to it. what else should i do ?

**Comment by pawangeek** [comment]
That's awesome @varuntumbe

**Comment by pawangeek** [comment]
@all-contributors please add @varuntumbe  for code

**Pull request merged**
