### PR TITLE
Adding proxy changer

### PR DESCRIPTION
**Pull request by lavinske**
For simplifying people that works on company that needed proxy for accessing their resource

### CODE REVIEW

**Comment by pawangeek** [comment]
Can you just brief which file is used for what purpose? Or host some of them in some cloud and mention them in README

**Comment by lavinske** [comment]
> Can you just brief which file is used for what purpose? Or host some of them in some cloud and mention them in README

Its like a shortcut for proxy settings for those whow works on pc that needs proxy to be turned on, I think that's a simpler way

**Comment by pawangeek** [comment]
Check this PR @Sacrezar

**Comment by Sacrezar** [comment]
wow

**Comment by Sacrezar** [comment]
Well, first thing first I can't launch it 
image
and I think there is no code to review because as far as I see, either it is dll, or it is library (like tk) 

And I'm not the kind to love the idea to pull easily recoverable files to the cloud, you wouldn't pull your node_module for example.

**Review by Sacrezar — CHANGES_REQUESTED** [review]
* Do something about the nine hundred files 😅 
* Can't launch it and can't review code

**Comment by Sacrezar** [comment]
No answer since 2 days and this PR was created without linked issue, I propose to close it

**Pull request closed without merging**
