### PR TITLE
Add URL shortener Script

### PR DESCRIPTION
**Pull request by hpnightowl**
# Pull Request Template

**script name** - URL Shortner

**What have you Changed**

Added a Script that will convert a given URL to a Tiny URL with the use of map funtion as mentioned in issue #7 

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [ ] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
Hey, can you please rename your readme file to README.md?

**Comment by hpnightowl** [comment]
ok

**Comment by hpnightowl** [comment]
@pawangeek done anything more?

**Comment by pawangeek** [comment]
Hey @hpnightowl, thanks for your contribution. Leave a star if you enjoy that :)

**Comment by hpnightowl** [comment]
# Preview
Screenshot (73)

**Comment by pawangeek** [comment]
@all-contributors please add @hpnightowl  for  code

**Comment by pawangeek** [comment]
@all-contributors please add @hpnightowl  for code

**Pull request merged**
