### PR TITLE
Keylogger using pynput module

### PR DESCRIPTION
**Pull request by thevirtualbuddy**
# Pull Request Template

**keylogger.py** -

**What have you Changed**
Added script

what you changed in the codebase.write here

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by Sacrezar** [comment]
Hey @thevirtualbuddy, try writing "recommended" instead of "recommended" (Readme, line 17). I think it iswwhy yyou don't pass the check

**Comment by thevirtualbuddy** [comment]
Thank you so much @Sacrezar :) 👍 
It was a great help.

**Comment by pawangeek** [comment]
Working as expected @thevirtualbuddy :)

**Comment by pawangeek** [comment]
@all-contributors add @thevirtualbuddy for code

**Comment by pawangeek** [comment]
@all-contributors add @Sacrezar for mentoring

**Comment by pawangeek** [comment]
@all-contributors add @Sacrezar for Mentoring

**Pull request merged**
