### PR TITLE
ImageAnnotator

### PR DESCRIPTION
**Pull request by Anustup900**
# Pull Request Template

**script name** - imageannotator

**Brief about script**
A Python script doing image annotation by the help of Open CV

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by thevirtualbuddy** [comment]
Hey @Anustup900 
Lint your code with flake8

**Review by thevirtualbuddy — COMMENTED** [review]
Lint your code with flake8 to pass the GitHub checks.

**Comment by pawangeek** [comment]
That's not correct @Anustup900

**Comment by Anustup900** [comment]
> That's not correct @Anustup900

Ok am soon editing and reuploading the code

**Comment by Anustup900** [comment]
Please Check now @pawangeek

**Review by Sacrezar — COMMENTED** [review]
Hey @Anustup900, thank you for your work.

Is this what you wanted @pawangeek ?
image

if that's it, it works.

For the readme, 
```bash
python install requirements.txt
python run imageannotater.py
```
didn't work for me, I had to do:
```
py -m pip install requirements.txt
py imageannotater image/path.jpg csv/path.csv
```

and when doing 
```
py -m pip install requirements.txt
```
I got: 
image
So I had to remove python from the requirements.txt

Otherwise, it's good. Just don't forget to add pandas into the requirements.txt

**Comment by Anustup900** [comment]
> Hey @Anustup900, thank you for your work.
> 
> Is this what you wanted @pawangeek ?
> image
> 
> if that's it, it works.
> 
> For the readme,
> 
> ```shell
> python install requirements.txt
> python run imageannotater.py
> ```
> 
> didn't work for me, I had to do:
> 
> ```
> py -m pip install requirements.txt
> py imageannotater image/path.jpg csv/path.csv
> ```
> 
> and when doing
> 
> ```
> py -m pip install requirements.txt
> ```
> 
> I got:
> image
> So I had to remove python from the requirements.txt
> 
> Otherwise, it's good. Just don't forget to add pandas into the requirements.txt

Thank you , so do i need to edit any thing ? or it will be merged ?

**Comment by pawangeek** [comment]
Yes, @Sacrezar that's what I want and @Anustup900 Just clear requirements.txt Remove python and add pandas in it. 
Then I will merge that PR

**Comment by Anustup900** [comment]
> Yes, @Sacrezar that's what I want and @Anustup900 Just clear requirements.txt Remove python and add pandas in it.
> Then I will merge that PR

Done @pawangeek

**Pull request merged**
