### PR TITLE
added Stopwatch

### PR DESCRIPTION
**Pull request by durgeshahire07**
# Pull Request Template

**Stopwatch** -

**Added Stopwatch**

Added a stop watch.

issue #136 

- [✓] This issue was assigned to me.
- [✓] One Change in one Pull Request
- [✓] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [✓] I am following clean code and Documentation and my code is well linted with flake8.
- [ ✓] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
check linting and code spell issues please

**Comment by durgeshahire07** [comment]
okay...i will create a new PR

**Comment by durgeshahire07** [comment]
fixed all the issues.

**Comment by pawangeek** [comment]
perfect @durgeshahire07

**Pull request merged**
