### PR TITLE
added script for sms_location

### PR DESCRIPTION
**Pull request by bunnysworld**
# Pull Request Template

**script name** -SMS location

**Brief about script**

- file name is sms_loc.py which uses Fast2Sms service to send the sms
- added requirements.txt 
- it uses [get.geos.js](https://get.geojs.io/v1/ip.json) to scrap your ip address
- scrap the long. and lat. data 
- added README.md provided with the screenshots

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
Hey, please remove .gitignore from the folder and check linting (flake8 here)

**Comment by bunnysworld** [comment]
hey @pawangeek as you said i had removed the .gitignore file and trying to resolve the linting issue but not getting any solution could you please help

**Comment by bunnysworld** [comment]
hey @pawangeek  done with my PR. Removed the .gitignore file and success the all checks

**Comment by pawangeek** [comment]
@bunnysworld, it's fine but can you please refork and do the changes, your PR should only include files of your folder, check, files changed in the PR for that

**Comment by bunnysworld** [comment]
ok @pawangeek

**Comment by bunnysworld** [comment]
making new PR this PR got some Linking issue

**Pull request closed without merging**
