### PR TITLE
Converting Text to sound 

### PR DESCRIPTION
**Pull request by Anustup900**
# Pull Request Template

**script name** - convert text to sound.py

**What have you Changed**

what you changed in the codebase.write here
Created Code Base
Updated Read Me with all steps
### Issue no.(must) - #
2 Issues Found : 
1.) Direct installing of the mentioned libraries in Anaconda generates Errors 
2.) Direct calling of the libraries in Google collab generates errors
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
Few suggestions @Anustup900. I created a self-check task list for you. Just tick mark them when completed

- [ ]  Change folder name tp sounf_to_text 
- [ ] Fix linting and spelling error
- [ ] Issue no. is something we open at issues #50 (so write that at issue(must)) space in PR template
- [ ] Replace your spaces in .py filename with _ and shorten it's name

**Comment by pawangeek** [comment]
Hey you can use http://pep8online.com/  for removing linting errors

**Comment by Anustup900** [comment]
> Few suggestions @Anustup900. I created a self-check task list for you. Just tick mark them when completed
> 
> * [ ]   Change folder name to sound_to_text
> * [ ]  Fix linting and spelling error
> * [ ]  Issue no. is something we open at issues #50 (so write that at issue(must)) space in PR template
> * [ ]  Replace your spaces in .py filename with _ and shorten it's name

**Review by pawangeek — CHANGES_REQUESTED** [review]
- Please remove sound_to_text empty file on root
- Remove folder "Converting text to sound" and add readme.md and requirements.txt to text_to_sound folder

**Comment by Anustup900** [comment]
> * Please remove sound_to_text empty file on root
> * Remove folder "Converting text to sound" and add readme.md and requirements.txt to text_to_sound folder

Done

**Review by pawangeek — COMMENTED** [review]
Perfectly fine now :)

**Comment by pawangeek** [comment]
Hey, thanks for your contribution @Anustup900 . Leave a star if you like the process and learn something about open source :)

**Comment by pawangeek** [comment]
@all-contributors please add @Anustup900 for code

**Pull request merged**
