### PR TITLE
Added a basic automation for Youtube

### PR DESCRIPTION
**Pull request by suubh**
# Pull Request Template

**script name** -youtube.py

**What have you Changed**

what you changed in the codebase.write here
Added a basic script for Youtube with proper README.md and requirements.txt

### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
Hey just remove those linting errors and you're done :)

**Comment by suubh** [comment]
Yes @pawangeek  working on that .

**Comment by pawangeek** [comment]
Hey you can use http://pep8online.com/ for removing flake8 errors

**Comment by suubh** [comment]
I did Its completely fine and correct . Wait I will do a new PR .

**Pull request closed without merging**
