### PR TITLE
Convert online articles to PDF

### PR DESCRIPTION
**Pull request by funbeedev**
# Pull Request Template

**script name** - articles_to_pdf.py

Convert online articles to PDF.

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by vivekascoder** [comment]
Please add the hacktoberfest-accepted .

**Comment by vivekascoder** [comment]
@pawangeek  Please check once.

**Comment by funbeedev** [comment]
Unsure why 'Greetings' check is failing. Let me know if I should correct anything. @pawangeek

**Comment by pawangeek** [comment]
Perfect @funbeedev and really appreciable for that headless arg

**Pull request merged**
