### PR TITLE
Added Rounded Image folder and updated Image Background Removal

### PR DESCRIPTION
**Pull request by avats101**
**script name** -
rounded_corner.py
image_background_subtractor.py

**Brief about script**
Added transparent feature in background subtractor and created rounded corner script with Pillow

### CODE REVIEW

**Comment by pawangeek** [comment]
Hey @avats101 Undo the changes in images_background folder and make the PR for rounded corner clean by fixing lint issues

**Comment by avats101** [comment]
> 
> 
> Hey @avats101 Undo the changes in images_background folder and make the PR for rounded corner clean by fixing lint issues

So should i make another issue for implementing background removal with transparent feature?

**Comment by pawangeek** [comment]
> > Hey @avats101 Undo the changes in images_background folder and make the PR for rounded corner clean by fixing lint issues
> 
> So should i make another issue for implementing background removal with transparent feature?

No not for now, we will do required changes later

**Comment by avats101** [comment]
> 
> 
> > > Hey @avats101 Undo the changes in images_background folder and make the PR for rounded corner clean by fixing lint issues
> > 
> > 
> > So should i make another issue for implementing background removal with transparent feature?
> 
> No not for now, we will do required changes later

Alright I'll store the feature locally for now.

**Pull request merged**
