### PR TITLE
Dns checker

### PR DESCRIPTION
**Pull request by aolaria**
# Pull Request Template

**script name** -

**What have you Changed**

what you changed in the codebase.write here

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

### CODE REVIEW

**Comment by pawangeek** [comment]
Will you please remove .DS_Store file

**Comment by aolaria** [comment]
> Will you please remove .DS_Store file

done

**Comment by pawangeek** [comment]
That's awesome @aolaria. Leave a star in repo  ⭐ if you enjoy this

**Comment by pawangeek** [comment]
@all-contributors add @aolaria for code

**Pull request merged**
